### ISSUE TITLE
Problem with "Auto Change Weather"

### ISSUE THREAD

**Issue by RavenPLAYER** [Monika-After-Story/MonikaModDev#4833]
As the title, I have a problem with the submod and I do not understand that it is because it has never been my specialty to understand what to program.

**Comment by RavenPLAYER** [comment]
![traceback txt_ Bloc de notas 04-10-2019 20_08_22](https://user-images.githubusercontent.com/55263957/66245295-4c163800-e6e3-11e9-90ab-5422d15f3a2a.png)

**Comment by RavenPLAYER** [comment]
![traceback txt_ Bloc de notas 04-10-2019 20_08_29](https://user-images.githubusercontent.com/55263957/66245306-56d0cd00-e6e3-11e9-8db3-cd2f2a2048f6.png)

**Comment by RavenPLAYER** [comment]
Somebody can help me? :(

**Comment by multimokia** [comment]
Try updating the submod, I released version 1.1 last night, should handle these connectivity issues.

**Comment by RavenPLAYER** [comment]
Okay, i'll try

**Comment by RavenPLAYER** [comment]
Ok, I did it, now I have to wait a bit because every time the weather had to change I got the error
(I download the Auto Sun Time too)

**Comment by multimokia** [comment]
Yeah, this decreases the time needed to change weather plus handles connection drops

**Comment by RavenPLAYER** [comment]
It doesn't work, I still get an error but this one is different

**Comment by RavenPLAYER** [comment]
![traceback txt_ Bloc de notas 04-10-2019 20_32_32](https://user-images.githubusercontent.com/55263957/66245751-33f3e800-e6e6-11e9-9939-abe2f8a55e6c.png)

**Comment by RavenPLAYER** [comment]
![traceback txt_ Bloc de notas 04-10-2019 20_35_02](https://user-images.githubusercontent.com/55263957/66245798-69003a80-e6e6-11e9-87b2-292e338f36be.png)

**Comment by RavenPLAYER** [comment]
The last line is in spanish, ("Se ha forzado la interrupción de una conexión existente por el host remoto") and it means ("The interruption of an existing connection by the remote host has been forced")

**Comment by Legendkiller21** [comment]
Open your browser and try to manually go to http://www.google.com . Does it load normally?

**Comment by RavenPLAYER** [comment]
Yep

**Comment by RavenPLAYER** [comment]
No vi ninguna respuesta, no me malinterpretes. Tampoco vi más errores, así que supongo que está solucionado

**Comment by RavenPLAYER** [comment]
I didn't see any answer, don't get me wrong. I also didn't see any more mistakes, so I guess it's fixed
