### ISSUE TITLE
"an exception has occurred"

### ISSUE THREAD

**Issue by ShiningDelooxe** [Monika-After-Story/MonikaModDev#5755]
[code]
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 1439, in script call
  File "game/event-handler.rpy", line 2086, in script call
  File "game/zz_consumables.rpy", line 1448, in script call
  File "game/zz_consumables.rpy", line 1460, in script
  File "game/zz_consumables.rpy", line 1465, in <module>
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpy", line 1439, in script call
  File "game/event-handler.rpy", line 2086, in script call
  File "game/zz_consumables.rpy", line 1448, in script call
  File "game/zz_consumables.rpy", line 1460, in script
  File "C:\Users\Rose\Desktop\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Rose\Desktop\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/zz_consumables.rpy", line 1465, in <module>
IndexError: list index out of range

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.11.2
[/code]

**Comment by multimokia** [comment]
This has been fixed with #5722 and will be in the next release. Sorry about that!

**Comment by ShiningDelooxe** [comment]
it doesn't really say how to fix it there from what i saw however i saw in another thread something about deleting .rpy files, is that the fix?

**Comment by multimokia** [comment]
If you click the quit button on the traceback and then load back in it should be fine again. However, if not, you might need to restore a persistent backup from before you gifted the extra amount of the consumable.

**Comment by ShiningDelooxe** [comment]
yeah I did that but it still doesn't work, there's a guide for how to restore a persistent isn't there? I think I knew how to do it but I forgot

**Comment by Booplicate** [comment]
What happens when you click the ignore button? When I tested, it just skipped a bit of dialogue after the traceback, but then the game worked just fine.
If that doesn't work for you, or you don't see the button. Then use [this guide](https://github.com/Monika-After-Story/MonikaModDev/wiki/FAQ#i-need-to-restore-an-older-persistent).

**Comment by ShiningDelooxe** [comment]
She says "I'm running out of ." "You wouldn't mind getting some more for me, would you?"
Before all this happened she said she was running out of coffee so maybe the event worked? idk

**Comment by Booplicate** [comment]
Okay, then I think you don't need to restore a backup. You should be fine.

**Comment by ShiningDelooxe** [comment]
one more question regarding that before I close up the issue, does that mean I have to gift more coffee or was that just a random event thing that doesn't really mean much?

**Comment by Booplicate** [comment]
The event triggers when she is low on something (coffee in your case). But before you saw the event, you were able to give her some coffee which broke the event (since it assumes she still doesn't have it).

You don't have to give her more coffee, and you won't see the event again in the near future (~2 weeks I think). But if that happens again, you'll need to `Ignore` it too. As multi said, the bug will be fixed in the next release.

**Comment by ShiningDelooxe** [comment]
ok tyvm!
